updated readme to correct ansible docker_arm repo
geerlingguy/ansible-role-docker_arm pull request #28
Opened 2021-08-16 13:49 UTC by AjayKumar4

![image](https://user-images.githubusercontent.com/12373874/129574236-780af28b-fff7-491c-85f8-fd8c2174d811.png)

2021-08-16 19:50 UTC, geerlingguy commented
The README is currently correct in that I want to point people to the Docker role if they _aren't_ on ARM, so instead, what if we change the first part of the line to read something like "If you want a more generic role for managing Docker on _non-ARM_ platforms like x86, please check out `geerlingguy.docker`"?

2021-08-26 15:46 UTC, ajaykumar4 commented
Sorry @geerlingguy for late response, I have updated the readme with respect to platform 
![image](https://user-images.githubusercontent.com/12373874/130994208-ab02909d-ab7c-4ebe-adc3-a18a3110f50e.png)

2021-08-27 03:43 UTC, geerlingguy requested changes

2021-08-27 03:43 UTC, geerlingguy commented on README.md
> +For ARM platforms like arm64, please check out [`geerlingguy.docker_arm`](https://galaxy.ansible.com/geerlingguy/docker_arm).
I think we can just drop this line (line 8 here)—it is redundant with the line on line 5 in the same file ("specially tailored for ARM-based computers like the Raspberry Pi").

2021-08-27 16:32 UTC, geerlingguy approved these changes

2021-08-27 16:32 UTC, merged

2021-08-27 16:32 UTC, geerlingguy commented
Thanks!